application: asciichan1
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "60d"

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(node_modules)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:
- url: /static
  static_dir: chan/static

- url: .*
  script: chan.app